sudo: required

env:
  - DOCKER_HOST_NETWORK=1

services:
  - docker

before_install:
  - docker pull maven

script:
  - docker build -t foxsec-pipeline:latest .
  - bin/m compile
  - bin/m spotless:check
  - bin/m test
